name: Continuos integration with PR

on:
  push:
    branches:
      - "features/**"
      - "github-action-test/**"

jobs:
  Build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
#      - name: Run test
#        run: npm test
#        env:
#          CI: true
      - name: Build project
        run: npm run build



    
