name: Continuos integration with PR

on:
  pull_request:
    branches:
      - "main"

jobs:
  run-test-and-build:
    runs-on: ubuntu-latest
    name: Build and Test in PR
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm run test
      - name: Build project
        run: npm run build



    
